import "@/styles/globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ThemeProvider } from "@/stores/ThemeContext";
import { LoadingProvider } from "@/stores/LoadingContext";
import LoadingSpinner from "@/components/LoadingSpinner";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased`}
        style={{ backgroundColor: 'lab(5 0.05 -4.54)' }}
      >
        <style dangerouslySetInnerHTML={{
          __html: `
            @media (max-width: 767px) {
              body {
                background-color: #111827 !important;
              }
            }
          `
        }} />
        <ThemeProvider>
          <LoadingProvider>
            <LoadingSpinner />
            {children}
          </LoadingProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
