import "@/styles/globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { ThemeProvider } from "@/stores/ThemeContext";
import { LoadingProvider } from "@/stores/LoadingContext";
import { PlanProvider } from "@/stores/PlanContext";
import LoadingSpinner from "@/components/LoadingSpinner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} antialiased`}
        style={{ backgroundColor: 'lab(5 0.05 -4.54)' }}
      >
        <style dangerouslySetInnerHTML={{
          __html: `
            @media (max-width: 767px) {
              body {
                background-color: #111827 !important;
              }
            }
          `
        }} />
        <ThemeProvider>
          <PlanProvider>
            <LoadingProvider>
              <LoadingSpinner />
              {children}
            </LoadingProvider>
          </PlanProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
